spring:
  application:
    name: Hotel-MicroService


  datasource:
    url: jdbc:mysql://localhost/demo
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Prateek@1998
    jpa:
      properties:
        hibernate:
          format_sql: true
      hibernate:
        ddl-auto: update
      show-sql: true
server:
  port: 8087

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka